---
openapi: 3.0.1
info:
  title: Rails Sample App
  version: v6
paths:
  "/":
    get:
      responses:
        '200':
          content: {}
  "/about":
    get:
      responses:
        '200':
          content: {}
  "/account_activations/{id}/edit":
    get:
      responses:
        '302':
          content: {}
      parameters:
      - name: email
        in: query
        schema:
          type: String
      - name: id
        in: path
        schema: {}
        required: true
  "/contact":
    get:
      responses:
        '200':
          content: {}
  "/help":
    get:
      responses:
        '200':
          content: {}
  "/login":
    get:
      responses:
        '200':
          content: {}
    post:
      responses:
        '200':
          content: {}
        '302':
          content: {}
  "/logout":
    delete:
      responses:
        '302':
          content: {}
  "/microposts":
    get:
      responses:
        '200':
          content: {}
    post:
      responses:
        '200':
          content: {}
        '302':
          content: {}
  "/microposts/{id}":
    delete:
      responses:
        '302':
          content: {}
        '303':
          content: {}
      parameters:
      - name: id
        in: path
        schema: {}
        required: true
  "/password_resets":
    post:
      responses:
        '200':
          content: {}
        '302':
          content: {}
  "/password_resets/new":
    get:
      responses:
        '200':
          content: {}
  "/password_resets/{id}":
    patch:
      responses:
        '200':
          content: {}
        '302':
          content: {}
      parameters:
      - name: id
        in: path
        schema: {}
        required: true
  "/password_resets/{id}/edit":
    get:
      responses:
        '200':
          content: {}
        '302':
          content: {}
      parameters:
      - name: email
        in: query
        schema: {}
      - name: id
        in: path
        schema: {}
        required: true
  "/relationships":
    post:
      responses:
        '200':
          content: {}
        '302':
          content: {}
  "/relationships/{id}":
    delete:
      responses:
        '200':
          content: {}
        '302':
          content: {}
      parameters:
      - name: id
        in: path
        schema: {}
        required: true
  "/signup":
    get:
      responses:
        '200':
          content: {}
  "/users":
    get:
      responses:
        '200':
          content: {}
        '302':
          content: {}
    post:
      responses:
        '200':
          content: {}
        '302':
          content: {}
  "/users/{id}":
    delete:
      responses:
        '302':
          content: {}
      parameters:
      - name: id
        in: path
        schema: {}
        required: true
    get:
      responses:
        '200':
          content: {}
      parameters:
      - name: id
        in: path
        schema: {}
        required: true
    patch:
      responses:
        '200':
          content: {}
        '302':
          content: {}
      parameters:
      - name: id
        in: path
        schema: {}
        required: true
  "/users/{id}/edit":
    get:
      responses:
        '200':
          content: {}
        '302':
          content: {}
      parameters:
      - name: id
        in: path
        schema: {}
        required: true
  "/users/{id}/followers":
    get:
      responses:
        '200':
          content: {}
        '302':
          content: {}
      parameters:
      - name: id
        in: path
        schema: {}
        required: true
  "/users/{id}/following":
    get:
      responses:
        '200':
          content: {}
        '302':
          content: {}
      parameters:
      - name: id
        in: path
        schema: {}
        required: true
components:
  securitySchemes: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
