name: AppMap Archive

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    # Keep the artifact up to date, as it will expire after 90 days.
    - cron: 1 1 1 * *
 
env:
  APPMAP_TELEMETRY_DISABLED: 'true'
  DISABLE_SPRING: 'true'

jobs:
  appmap_archive_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
      - name: Install AppMap tools
        run: |
          curl -L -o /tmp/appmap https://github.com/getappmap/appmap-js/releases/download/%40appland%2Fappmap-preflight-v1.0-pre.1/appmap-preflight-linux-x64
          chmod +x /tmp/appmap
      - name: Yarn install
        run: yarn install
      - name: Rails test setup
        run: |
          ./bin/rails db:create
          ./bin/rails db:test:prepare
          ./bin/webpack
      - name: Run tests
        run: ./bin/rails test
      - name: Archive AppMaps
        uses: getappmap/archive-appmap-action@v1-pre.8
        id: archive-appmaps
        with:
          verbose: true
