name: AppMap Archive

on:
  pull_request:
  schedule:
    # Keep the artifact up to date, as it will expire after 90 days.
    - cron: 1 1 1 * *
 
env:
  APPMAP_TELEMETRY_DISABLED: 'true'
  DISABLE_SPRING: 'true'

jobs:
  appmap_archive_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: # This is needed on a PR, because the checkout action doesn't fetch the base or head branches
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
      - name: Prepare bundle for AppMap installation
        run: bundle config unset deployment
      - name: Install AppMap tools
        uses: getappmap/install-appmap-action@v1-pre.5
        with:
          project-type: bundler
          verbose: true
      # - name: Commit AppMap configuration
      #   uses: EndBug/add-and-commit@v9
      - name: Yarn install
        run: yarn install
      - name: Rails test setup
        run: |
          ./bin/rails db:create
          ./bin/rails db:test:prepare
          ./bin/webpack
      - name: Run tests
        run: ./bin/rails test || true
      - name: Archive AppMaps
        uses: getappmap/archive-appmap-action@v1-pre.8
        with:
          commit-sha: ${{ github.event.pull_request.head.sha }}
          verbose: true
