name: AppMap Preflight

on:
  pull_request:
    types:
      - closed

env:
  APPMAP_TELEMETRY_DISABLED: 'true'

jobs:
  appmap_archive_main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install AppMap
        uses: getappmap/install-appmap-action@v1-pre.3
        id: install-appmap
        with:
          verbose: true
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
      - name: Yarn install
        run: yarn install
      - name: Rails test setup
        run: |
          ./bin/rails db:migrate
          ./bin/webpack
      - name: Run tests
        run: ./bin/rails test
      - name: Archive AppMaps
        uses: getappmap/archive-appmap-action@v1-pre.7
        id: archive-appmaps
        with:
          verbose: true
