name: appmap-analysis

on:
  pull_request:
  push:
    branches:
      - appmap-e2e
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Enable appmap gem update
        run: bundle config unset deployment 

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Prepare bundle for AppMap installation
        run: bundle config unset deployment
      
      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          project-type: bundler # Choose the type of your project here:
                        # bundler, maven, gradle, pip, pipenv, poetry,
                        # yarn, npm, etc.
  
      - name: Yarn install
        run: yarn install

      - name: Rails test setup
        run: |
          ./bin/rails db:migrate
          ./bin/webpack

      - name: Run tests
        run: ./bin/rails test

      - name: Save AppMaps
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ./tmp/appmap
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}
  
  appmap-analysis:
    if: always()
    needs: [test] # You may need to change this to match the name of the step that runs your tests.
    uses: getappmap/analyze-action/.github/workflows/appmap-analysis.yml@v1
    permissions:
      actions: read
      contents: read
      checks: write
      pull-requests: write
