name: appmap-analysis

on:
  pull_request:
  push:
    branches:
      - appmap-e2e
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Enable appmap gem update
        run: bundle config unset deployment
      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          project-type: bundler
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "ci: Add AppMap language agent and appmap.yml"

      - name: Yarn install
        run: yarn install

      - name: Rails test setup
        run: |
          ./bin/rails db:migrate
          ./bin/webpack

      - name: Run tests
        run: ./bin/rails test

      - name: Save AppMaps
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ./tmp/appmap
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

      # Begin AppMap bootstrap archive step
      - name: Archive AppMaps
        id: appmap-bootstrap-archive-appmaps
        uses: getappmap/archive-action@v1
        with:
          revision: ${{ github.event.pull_request.base.sha }}
      # End AppMap bootstrap archive step
  
  appmap-analysis:
    if: always()
    needs: [test]
    uses: getappmap/analyze-action/.github/workflows/appmap-analysis.yml@v1
    permissions:
      actions: read
      contents: write
      checks: write
      pull-requests: write