name: appmap-analysis

on:
  pull_request:
  push:
    branches:
      - appmap-e2e
  schedule:
    - cron: '0 0 * * 0'

permissions:
  # Allows the EndBug/add-and-commit step to commit the package manager changes,
  # adding the AppMap language library and configuration file appmap.yml.
  # Once the EndBug/add-and-commit is removed, this permission can be removed, 
  # unless you need it for other reasons.
  contents: write
  # Allows the getappmap/archive-action to write a PR comment with the 
  # AppMap configuration status.
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      # Begin AppMap CI language agent installation
      # This snippet can be safely removed once the AppMap language agent has been
      # added to the project dependencies, and appmap.yml has been created.
      - name: Enable appmap gem update
        run: bundle config unset deployment
      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          project-type: bundler
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "ci: Add AppMap language agent and appmap.yml"
      # End AppMap CI language agent installation

      - name: Yarn install
        run: yarn install

      - name: Rails test setup
        run: |
          ./bin/rails db:migrate
          ./bin/webpack

      - name: Run tests
        run: ./bin/rails test

      - name: Save AppMaps
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ./tmp/appmap
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}
  
  appmap-analysis:
    if: always()
    needs: [test] # You may need to change this to match the name of the step that runs your tests.
    uses: getappmap/analyze-action/.github/workflows/appmap-analysis.yml@v1
    permissions:
      actions: read
      contents: write
      checks: write
      pull-requests: write